# 🆓 Codemagic FREE iOS Build Configuration
# ⚠️ IMPORTANT: This builds iOS apps WITHOUT Apple Developer account
# ✅ Generates .ipa files for testing
# ❌ Cannot install on real iPhone (requires $99/year Apple Developer account)
# ✅ Can test in iOS Simulator
# ✅ Perfect for development and testing

workflows:
  ios-workflow-free:
    name: 🆓 Free iOS Build (No Apple Developer Account)
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "3.16.0"
      xcode: latest
      cocoapods: default
    scripts:
      - name: 🚀 Install Flutter
        script: |
          echo "Installing Flutter $FLUTTER_VERSION..."
          flutter --version
          flutter config --no-analytics
          flutter doctor -v
          
      - name: 📦 Get Flutter dependencies
        script: |
          echo "Getting Flutter dependencies..."
          flutter pub get
          
      - name: 🔍 Flutter analyze
        script: |
          echo "Running Flutter analyze..."
          flutter analyze
          
      - name: 🧪 Flutter unit tests
        script: |
          echo "Running Flutter tests..."
          flutter test
          
      - name: 📱 Install CocoaPods
        script: |
          echo "Installing CocoaPods dependencies..."
          find . -name "Podfile" -execdir pod install \;
          
      - name: 🏗️ Build iOS App for Simulator (FREE)
        script: |
          echo "Building iOS app for simulator (no code signing required)..."
          flutter build ios --simulator --debug
          
      - name: 📦 Create Simulator Build Archive
        script: |
          echo "Creating simulator build archive..."
          cd build/ios/iphonesimulator
          zip -r ../../../ios-simulator-build.zip .
          cd ../../../
          
      - name: 🏗️ Build Unsigned IPA (For Development)
        script: |
          echo "Building unsigned IPA for development..."
          flutter build ios --debug --no-codesign
          
          # Create IPA manually (since we can't use flutter build ipa without signing)
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../ios-unsigned-app.zip Payload/
          cd ../../../
          
    artifacts:
      - build/ios/iphonesimulator/
      - ios-simulator-build.zip
      - build/ios/iphoneos/Runner.app
      - ios-unsigned-app.zip
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      scripts:
        - name: 📧 Notify Success
          script: |
            echo "🎉 iOS build completed successfully!"
            echo "📱 Simulator build: Available for iOS Simulator testing"
            echo "📦 Unsigned IPA: Available for development (cannot install on real iPhone)"
            echo "⚠️  To install on real iPhone, you need Apple Developer account ($99/year)"

  # Optional: Build for multiple iOS versions
  ios-multi-version:
    name: 🔄 Build for Multiple iOS Versions
    max_build_duration: 90
    environment:
      vars:
        FLUTTER_VERSION: "3.16.0"
      xcode: latest
      cocoapods: default
    scripts:
      - name: 🚀 Install Flutter
        script: |
          flutter --version
          flutter pub get
          
      - name: 📱 Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
          
      - name: 🏗️ Build for iOS 15.0
        script: |
          flutter build ios --simulator --debug --target-platform ios --ios-version 15.0
          cd build/ios/iphonesimulator
          zip -r ../../../ios-15-build.zip .
          cd ../../../
          
      - name: 🏗️ Build for iOS 16.0
        script: |
          flutter build ios --simulator --debug --target-platform ios --ios-version 16.0
          cd build/ios/iphonesimulator
          zip -r ../../../ios-16-build.zip .
          cd ../../../
          
      - name: 🏗️ Build for iOS 17.0
        script: |
          flutter build ios --simulator --debug --target-platform ios --ios-version 17.0
          cd build/ios/iphonesimulator
          zip -r ../../../ios-17-build.zip .
          cd ../../../
          
    artifacts:
      - ios-15-build.zip
      - ios-16-build.zip
      - ios-17-build.zip