// Mocks generated by Mockito 5.4.4 from annotations
// in forever_us_in_love/test/features/auth/data/datasources/auth_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:forever_us_in_love/core/network/auth_api_client.dart' as _i4;
import 'package:forever_us_in_love/features/auth/data/models/requests/login_request.dart'
    as _i7;
import 'package:forever_us_in_love/features/auth/data/models/requests/register_request.dart'
    as _i6;
import 'package:forever_us_in_love/features/auth/data/models/requests/resend_code_request.dart'
    as _i9;
import 'package:forever_us_in_love/features/auth/data/models/requests/verify_code_request.dart'
    as _i8;
import 'package:forever_us_in_love/features/auth/data/models/responses/auth_response.dart'
    as _i2;
import 'package:forever_us_in_love/features/auth/data/models/responses/verification_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerificationResponse_1 extends _i1.SmartFake
    implements _i3.VerificationResponse {
  _FakeVerificationResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i4.AuthApiClient {
  MockAuthApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthResponse> register(_i6.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<Map<String, dynamic>> checkUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUsername,
          [username],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> suggestUsernames(
    String? firstName,
    String? lastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #suggestUsernames,
          [
            firstName,
            lastName,
          ],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.AuthResponse> login(_i7.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logoutAll() => (super.noSuchMethod(
        Invocation.method(
          #logoutAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logoutDevice(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #logoutDevice,
          [deviceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getSessions() => (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> deleteSession(String? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [sessionId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResponse> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.VerificationResponse> verifyEmailCode(
          _i8.VerifyCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmailCode,
          [request],
        ),
        returnValue: _i5.Future<_i3.VerificationResponse>.value(
            _FakeVerificationResponse_1(
          this,
          Invocation.method(
            #verifyEmailCode,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.VerificationResponse>);

  @override
  _i5.Future<void> sendPhoneVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendPhoneVerification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.VerificationResponse> verifyPhoneCode(
          _i8.VerifyCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneCode,
          [request],
        ),
        returnValue: _i5.Future<_i3.VerificationResponse>.value(
            _FakeVerificationResponse_1(
          this,
          Invocation.method(
            #verifyPhoneCode,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.VerificationResponse>);

  @override
  _i5.Future<Map<String, dynamic>> resendCode(_i9.ResendCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendCode,
          [request],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> forgotPassword(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [request],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> changePassword(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [request],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> checkPasswordStrength(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPasswordStrength,
          [request],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.AuthResponse> googleLogin(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #googleLogin,
          [request],
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #googleLogin,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> facebookLogin(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #facebookLogin,
          [request],
        ),
        returnValue: _i5.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #facebookLogin,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<Map<String, dynamic>> createWorkflowRun(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkflowRun,
          [request],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getWorkflowRun(String? workflowRunId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkflowRun,
          [workflowRunId],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}
